### ISSUE TITLE
[BE] Define tech stack

### ISSUE THREAD

**Issue by nancylee713** [nancylee713/AILanguageTutor_BE#1]
Decide which languages, frameworks, tools that we will use for this project by Sunday (12/15).
Currently, candidates are:
- Python & Django (if we're implementing machine learning)
- Node
- GraphQL
- Others

Default:
- Ruby, Rails, Postgres

**Comment by sschipke** [comment]
I would also propose Python with Flask on top of GraphQL. They seem to be relatively easy together. Depending on what we need.
